

puts "creating restaurants..."

lilia = Restaurant.create(name: "Lilia", image_url: "https://assets.bwbx.io/images/users/iqjWHBFdfxIU/iUVX58Y0s2JA/v1/1200x-1.jpg", cuisine: "Italian", price_point: "$$$", description: "Lilia brings the best of Italy to Williamsburg where wood-fired seafood, hand crafted pastas, classic Italian cocktails and warm hospitality come together to create a casual dining experience.", reviews: "★★★★★", location: "Brooklyn", address: "567 Union Ave, Brooklyn, NY 11211")
oxomoco = Restaurant.create(name: "Oxomoco", image_url: "https://cdn.vox-cdn.com/thumbor/7Fi5DhqOmlM8_QPIrhbVNBKj94M=/0x0:5760x3840/1200x675/filters:focal(2420x1460:3340x2380)/cdn.vox-cdn.com/uploads/chorus_image/image/59950037/untitled_1.0.jpg", cuisine: "Mexican", price_point: "$$", description: "When you subscribe to Oxomoco you'll access the Michelin Starred, specially crafted cuisine that only Chef Justin Bazdarich and his team can provide. Explore the ingredients and flavors of Mexico perfectly paired with cocktails as well as exclusive in-house events, cooking classes, and more to experience the greatness that is Oxomoco.", reviews: "★★★★★", location: "Brooklyn", address: "128 Greenpoint Ave, Brooklyn, NY 11222")
maison = Restaurant.create(name: "Maison Premiere", image_url: "https://images.squarespace-cdn.com/content/v1/53bff3c3e4b0fd8b51088a58/1410235693095-4AFNL6LQARB1G0AOB4OX/image-asset.jpeg?format=1000w", cuisine: "Oyster Bar", price_point: "$$$", description: "Maison Premiere is rooted in the traditions and ceremony of oyster bars and absinthe cafés, where at-hand service paired with frank advice about daily shellfish and quenching wines serve as well as the recipes from old bar manuals.", reviews: "★★★★★", location: "Brooklyn", address: "298 Bedford Ave, Brooklyn, NY 11249")
 bonnies = Restaurant.create(name: "Bonnie's", image_url: "https://cdn.vox-cdn.com/thumbor/C5rwdiGDlXzPLqIO7ukn8esgCJg=/0x0:7952x5304/1720x0/filters:focal(0x0:7952x5304):format(webp):no_upscale()/cdn.vox-cdn.com/uploads/chorus_asset/file/23060559/AF_Bonnies_1.jpg", cuisine: "Chinese", price_point: "$$", description: "Brooklyn-born chef Calvin Eng named his modestly sized Williamsburg Cantonese-American restaurant after his mom — who, he says, taught him everything he knows about classic Cantonese cooking, with a uniquely New York lens. Pro tip: Save room for the showstopping fish entrée.", reviews: "★★★★★", location: "Brooklyn", address: "398 Manhattan Ave, Brooklyn, NY 11211")
 diner = Restaurant.create(name: "Diner", image_url: "https://image.resy.com/3/003/2/2038/86548720a7c611dc5cb521501378b1e3aaba3cb3/jpg/1600x1600", cuisine: "American", price_point: "$$", description: "Diner is the definitive Brooklyn restaurant (after all, it was Andrew Tarlow's first). Rife with hipster quirks, and keeper of a burger that rivals that of its neighbor across the street (read: Peter Luger), it's earned iconic status.", reviews: "★★★★", location: "Brooklyn", address: "85 Broadway, Brooklyn, NY 11249")
 falansi = Restaurant.create(name: "Falansi", image_url: "https://images.squarespace-cdn.com/content/v1/552d7a52e4b0ede95614e9c8/1510163566710-P23JGDNS83F7KX334PJ9/Falansai+Passerguide58.jpg", cuisine: "Vietnamese", price_point: "$$", description: "Because when a Blue Hill at Stone Barns alum takes over a trusted Vietnamese staple, sparks fly. Under new chef and owner Eric Tran, Falansai turns heads with an electric array of Vietnamese American dishes that highlight fermentation, house-made charcuterie, and local purveyors. Pro tip: Every meal should begin with the confit duck necks.", reviews: "★★★★★", location: "Brooklyn", address: "112 Harrison Pl, Brooklyn, NY 11237")
 robertas = Restaurant.create(name: "Roberta's", image_url: "https://nypost.com/wp-content/uploads/sites/2/2020/11/120716_Roberta_s_Pizzeria_death_threatPM.jpg?quality=75&strip=all", cuisine: "American", price_point: "$$", description: "What can be said about Roberta's that hasn't yet been said? Brooklyn's groundbreaking pizzeria ushered in a new era of New York-style pizza when it first opened in 2008, and it remains a standard bearer for truly exceptional pizza, as well as standout pastas, a killer natural wine list, and inventive market-driven small plates. Nothing beats coming here, to the original location, right here in Bushwick, where it all started.", reviews: "★★★★★", location: "Brooklyn", address: "6 Grand St, Brooklyn, NY 11249")
 llama_inn = Restaurant.create(name: "Llama Inn", image_url: "https://s3.amazonaws.com/cuag/gallery_resources/000/020/491/original-6e871dbd6b2b80baf0cac2ef8b4c380e.jpg", cuisine: "Peruvian", price_point: "$$", description: "The deliciously complex and forward-thinking Peruvian cuisine would be enough, yet what's more is that Llama Inn is a very fun restaurant, very worthy of a night on the town.", reviews: "★★★★★", location: "Brooklyn", address: "50 Withers St, Brooklyn, NY 11211")
 di_an_di = Restaurant.create(name: "Di An Di", image_url: "https://byoblikeaboss.com/wp-content/uploads/2018/11/20180515_GH_DIANDI_1019.0.jpg", cuisine: "Vietnamese", price_point: "$$", description: "Light, lush, and lip-smackingly good, Di An Di is the Vietnamese restaurant you'll want to take all of your friends to.", reviews: "★★★★★", location: "Brooklyn", address: "68 Greenpoint Ave, Brooklyn, NY 11222")
 santa_fe = Restaurant.create(name: "Santa Fe BK", image_url: "https://www.bkmag.com/wp-content/uploads/2021/10/sfbk-3-scaled.jpg", cuisine: "Southwest", price_point: "$", description: "After charming Brooklynites with their green chile cheeseburgers and breakfast burritos, Santa Fe BK owners Melissa Klein and John Watterberg now have a full all-day menu of Santa Fe-style favorites, including Christmas-style smothered burritos, green chile chicken enchiladas, pozole, a green chile queso dip, margaritas, and off-menu sopapillas, among other dishes.", reviews: "★★★★★", location: "Brooklyn", address: "178 N 8th St, Brooklyn, NY 11211")


le_cou_cou = Restaurant.create(name: "Le Cou Cou", image_url: "https://static01.nyt.com/images/2016/11/02/dining/02REST-LECOUCOU-slide-2Z7W/02REST-LECOUCOU-slide-2Z7W-jumbo.jpg", cuisine: "French", price_point: "$$$$", description: "After taking Paris by storm, internationally acclaimed chef Daniel Rose returns home with Le Coucou. A gracious modern nod to fine European gastronomy, Rose shrinks the intercontinental divide separating the City of Light and the Big Apple, proving that the true essence of fine French dining can thrive in any time zone.", reviews: "★★★★★", location: "Manhattan", address: "138 Lafayette St, New York, NY 10013")
rosemarys = Restaurant.create(name: "Rosemary's", image_url: "https://media.architecturaldigest.com/photos/60e33c2983afe4fd18137304/master/w_1600%2Cc_limit/rosemarys_0421_lizclayman_211.jpg", cuisine: "Italian", price_point: "$$", description: "The original location of Rosemary's, opened in 2012, is a Greenwich Village staple for seasonal salads, handmade pastas, our rooftop garden and view overlooking Jefferson Market Garden.", reviews: "★★★★", location: "Manhattan", address: "18 Greenwich Ave, New York, NY 10011")
jojo = Restaurant.create(name: "Jojo", image_url: "https://s3.amazonaws.com/jojorestaurantnyc/JoJo-FR-11_1600x1000-1513623619206.jpg", cuisine: "French", price_point: "$$$", description: "Est. 1991. Jean-Georges' first restaurant, and named after his childhood nickname that his mother would call him, has recently reopened in a duplex townhouse on the Upper East Side, creating a modern and fresh design, yet still maintaining an understated, warm and friendly atmosphere. JoJo is a simple and casual neighborhood friendly restaurant serving a farm to table menu with mostly organic and local ingredients.", reviews: "★★★★★", location: "Manhattan", address: "160 E 64th St, New York, NY 10065")
don_angie = Restaurant.create(name: "Don Angie", image_url: "https://cdn.vox-cdn.com/thumbor/9gAX5on_C0iSBeuQibW2F8nG2xw=/0x0:4500x3000/1200x0/filters:focal(0x0:4500x3000):no_upscale()/cdn.vox-cdn.com/uploads/chorus_asset/file/9430693/20171008_DONANGIE_1014.jpg", cuisine: "Italian", price_point: "$$", description: "Don Angie remains on permanent Notify status for many, and for good reason. Since opening in 2017, the Michelin-starred West Village hit has won over diners with a fun vibe and one-of-a-kind fare — stuffed garlic flatbread, pepperoni fried rice, lasagna for two, and so much more.", reviews: "★★★★★", location: "Manhattan", address: "103 Greenwich Ave, New York, NY 10014")
forsythia = Restaurant.create(name: "Forsythia", image_url: "https://byoblikeaboss.com/wp-content/uploads/2019/11/Screen-Shot-2019-11-13-at-1.59.39-PM.png", cuisine: "Italian", price_point: "$$", description: "Forsythia is an upcoming Italian restaurant at Nine Stanton Street.  When you step into our restaurant, we want you to feel what we felt when we lived in Italy and were welcomed into a home for dinner. Our aim is to provide excellent, hand-crafted Italian comfort food in a considerate relaxing environment and, for the time-being, bring that experience to your house.", reviews: "★★★★★", location: "Manhattan", address: " 9 Stanton St, New York, NY 10002")
fairfax = Restaurant.create(name: "Fairfax", image_url: "https://images.getbento.com/accounts/2ae11b6f4bee52136ca41a5f8dd07d08/media/images/1656669994FairfaxNYC_370.jpg?w=1800&fit=max&auto=compress,format&h=1800", cuisine: "American", price_point: "$$$", description: "FAIRFAX is a relaxed and cozy all day cafe, wine bar and restaurant serving seasonal fare starting at 8am everyday.", reviews: "★★★★★", location: "Manhattan", address: "234 West 4th Street, New York, NY 10014")
le_trois = Restaurant.create(name: "Les Trois Chevaux", image_url: "https://cdn.vox-cdn.com/thumbor/sOjzKlagtvq5P_efObjaPPSD0WU=/0x0:4032x3024/1200x900/filters:focal(1694x1190:2338x1834):no_upscale()/cdn.vox-cdn.com/uploads/chorus_image/image/69668963/PXL_20210707_192817315.MP.0.jpg", cuisine: "French", price_point: "$$$$", description: "Leave it to Angie Mar to take old-school French dining in the vein of Lutèce, and make it distinctively hers. With Les Trois Chevaux, the chef-owner of Beatrice Inn fame is letting her creativity run wild in a beautifully designed space that lives and breathes downtown New York. Expect crystal chandeliers, a carving station where roasted pheasant is served, and a collection of vintage Yves Saint Laurent jackets, should your party need one. Needless to say: Dress to impress.", reviews: "★★★★★", location: "Manhattan", address: "283 W 12th St, New York, NY 10014")
parcelle= Restaurant.create(name: "Parcelle", image_url: "https://gothammag.com/get/files/image/galleries/1_Parcelle_P8272.jpg", cuisine: "Wine", price_point: "$$", description: "The team behind online wine retailer Parcelle now has a downtown spot that's perfect for a midday glass of wine and access to some of the city's rarest vintages. At night, the shop transforms into a lively bar and restaurant with more than 500 bottles to choose from and a highly snackable menu, plus a full dinner menu, offered Mondays through Saturdays, from chef Ron Yan.", reviews: "★★★★★", location: "Manhattan", address: "135 Division St, New York, NY 10002")
wayan = Restaurant.create(name: "Wayan", image_url: "https://image.resy.com/3/003/2/4599/a0653c7a3d9a74341918fb45423006c908cdef85/jpg/1600x1600", cuisine: "Southeast Asian", price_point: "$$", description: "Because Wayan is the love story of Ochi and Cedric Vongerichten. Think Indonesian flavors (from Ochi's birthplace, Jakarta) paired with a bold French touch (the Vongerichten gene no doubt), for a truly delectable feast.", reviews: "★★★★★", location: "Manhattan", address: "20 Spring St, New York, NY 10012")
sadelles = Restaurant.create(name: "Sadelle's", image_url: "https://image.resy.com/3/003/2/29967/f42629956ba64e06a92e9f30112613574b176148/jpg/1600x1600", cuisine: "Brunch", price_point: "$$", description: "Team Carbone's splashy response to the Jewish deli of lore, Sadelle's is where expertly sliced lox is delivered on delicate three-tiered stands, and towers of hot, freshly baked bagels waltz through the buzzing dining room. This is decidedly not your bubbe's kitchen (unless yours had caviar service), but the comfort-laden food is spectacular.", reviews: "★★★★", location: "Manhattan", address: "463 W Broadway, New York, NY 10012")




puts "creating users..."

user1 = User.create(username: "Siobhan", password: "123")
user2 = User.create(username: "George", password: "123")
user3 = User.create(username: "Will", password: "123")
user4 = User.create(username: "YY", password: "123")
user5 = User.create(username: "Steven", password: "123")


puts "creating attended..."
Attend.create(user_id: 1, restaurant_id: 2, been_to: true)
Attend.create(user_id: 1, restaurant_id: 1, been_to: false)
Attend.create(user_id: 2, restaurant_id: 1, been_to: true)
Attend.create(user_id: 3, restaurant_id: 1, been_to: false)
Attend.create(user_id: 4, restaurant_id: 2, been_to: true)
Attend.create(user_id: 5, restaurant_id: 2, been_to: true)

puts "creating wishlist..."
# Wishlist.create(user_id: 3, restaurant_id: 2, ranking: 1)
# Wishlist.create(user_id: 4, restaurant_id: 1, ranking: 1)
# Wishlist.create(user_id: 5, restaurant_id: 1, ranking:1) 
# Wishlist.create(user_id: 3, restaurant_id: 2, ranking: 2)



puts "✅ Done seeding!"